export const products = [
  {
    id: 1,
    name: "Fresh Apples",
    category: "Fruits",
    price: 350,
    unit: "1 kg",
    emoji: "🍎",
  },
  {
    id: 2,
    name: "Fresh Bananas",
    category: "Fruits",
    price: 220,
    unit: "1 dozen",
    emoji: "🍌",
  },
  {
    id: 3,
    name: "Fresh Carrots",
    category: "Vegetables",
    price: 180,
    unit: "1 kg",
    emoji: "🥕",
  },
  {
    id: 4,
    name: "Fresh Potatoes",
    category: "Vegetables",
    price: 150,
    unit: "1 kg",
    emoji: "🥔",
  },
  {
    id: 5,
    name: "Fresh Milk",
    category: "Dairy",
    price: 250,
    unit: "1 Liter",
    emoji: "🥛",
  },
  {
    id: 6,
    name: "Fresh Bread",
    category: "Bakery",
    price: 160,
    unit: "1 Pack",
    emoji: "🍞",
  },
  {
    id: 7,
    name: "Orange Juice",
    category: "Beverages",
    price: 320,
    unit: "1 Liter",
    emoji: "🧃",
  },
  {
    id: 8,
    name: "Chocolate Cookies",
    category: "Snacks",
    price: 180,
    unit: "1 Pack",
    emoji: "🍪",
  },
];